version: '3'

services:
  db:
    container_name: taxidispatch_db
    image: postgres:16.3-alpine3.20
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  postgres-db:
    external: false
